No gh-actions k3s

diff --git a/.github/workflows/k3s-actions.yaml b/.github/workflows/k3s-actions.yaml
--- a/.github/workflows/k3s-actions.yaml
+++ b/.github/workflows/k3s-actions.yaml
@@ -53,18 +53,21 @@ jobs:
       - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
       - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
 
-      - uses: debianmaster/actions-k3s@master
-        id: k3s
-        with:
-          version: 'v1.21.2-k3s1'
-
-      - name: Setup tmate session
-        uses: mxschmitt/action-tmate@v3
+        # This causes Multus to fail with:
+        ## Error: failed to generate container "0347a3376766dcc041d0a929e0c6498b70ccbef00d91acff3eee47932be2e0f6" spec: failed 
+        ## to generate spec: path "/var/lib/rancher/k3s/data/current/bin" is mounted on "/var/lib/rancher/k3s" but it is not a shared mount
+        # - uses: debianmaster/actions-k3s@master
+        #   id: k3s
+        #   with:
+        #     version: 'v1.21.2-k3s1'
 
       - name: Check out repository code
         uses: actions/checkout@v3
       - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
       - run: echo "🖥️ The workflow is now ready to test your code on the runner."
+
+      - name: Setup tmate session
+        uses: mxschmitt/action-tmate@v3
 
       - name: Sleep forever
         run: |
@@ -74,8 +77,8 @@ jobs:
         run: |
           source tests/environment.sh
 
-          sudo -E bash -eo pipefail tests/01-prepare-github-k3s.sh
-          #sudo -E bash -eo pipefail tests/01-prepare.sh
+          #sudo -E bash -eo pipefail tests/01-prepare-github-k3s.sh
+          sudo -E bash -eo pipefail tests/01-prepare.sh
           sudo -E bash -eo pipefail tests/02-annotations-handling.sh
           sudo -E bash -eo pipefail tests/03-install-linkerd-control-plane.sh
           sudo -E bash -eo pipefail tests/04-install-linkerd-viz.sh
